### ISSUE TITLE
SF Font must be present on your Mac?

### ISSUE THREAD

**Issue by BtStSoft** [rushairer/IconShopFeedbacks#1]
All symbols appeared bold even after selecting thin. Disappointed I downloaded the SF Symbol app from Apple. Had to do the SVG export and creation of PNG files myself using that app. So I reinstalled IconShop and suddenly it all worked!! Love the features!
So somehow the app only works correctly when the right fonts are installed.

**Comment by rushairer** [comment]
Thanks for your feedback!

Please tell me the version of your system OS.

I develop under the latest system.
There may be font problems with earlier systems. I need more testing...

**Comment by BtStSoft** [comment]
I use macOS Mojave Version 10.14.6

**Comment by rushairer** [comment]
@BtStSoft Fixed this bug. Please update to version 1.0.1.
